export const ALLOWED_TYPES = {
  "Dedicated To": {
    type: "text",
  },
  "Rhyming Scheme": {
    type: "enum",
    values: [
      "alternate rhyme",
      "ballade",
      "coupled rhyme",
      "monorhyme",
      "enclosed rhyme",
      "terza rima",
      "limerick",
      "villanelle",
    ],
  },
  "Poem Type": {
    type: "enum",
    values: [
      "limerick",
      "haiku",
      "free verse",
      "sonnet",
      "blank verse",
      "heroic couplet",
    ],
  },
  "Foot": {
    type: "enum",
    link: "https://en.wikipedia.org/wiki/Foot_(prosody)",
    values: [
      "pyrrhus",
      "dibrach",
      "iamb",
      "trochee",
      "spondee",
      "tribach",
      "dactyl",
      "amphibrach",
      "anapest",
      "bacchius",
      "cretic",
      "antibacchius",
      "molossus",
      "tetrabrach",
      "primus",
      "secundus paeon",
      "tertius paeon",
      "quartus paeon",
      "major ionic, double trochee",
      "minor ionic, double iamb",
      "ditrochee",
      "diiamb",
      "choriamb",
      "antispast",
      "first epitrite",
      "second epitrite",
      "third epitrite",
      "fourth epitrite",
      "dispondee",
    ],
  },
  "Meter": {
    type: "enum",
    link: "https://en.wikipedia.org/wiki/Metre_(poetry)",
    values: [
      "triameter",
      "tetrameter",
      "pentameter",
      "heptameter",
    ],
  },
};
